this is jacob's jupyter notebook

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../data/trash_hauler_report.csv')

In [4]:
df.info()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20226 entries, 0 to 20225
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Request Number    20226 non-null  int64
 1   Date Opened       20226 non-null  object
 2   Request           20226 non-null  object
 3   Description       20195 non-null  object
 4   Incident Address  20217 non-null  object
 5   Zip Code          20151 non-null  float64
 6   Trash Hauler      19325 non-null  object
 7   Trash Route       19279 non-null  object
 8   Council District  20177 non-null  float64
 9   State Plan X      20198 non-null  float64
 10  State Plan Y      20198 non-null  float64
dtypes: float64(4), int64(1), object(6)
memory usage: 1.7+ MB

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207.0,RED RIVER,3205,2.0,1.727970e+06,686779.478089
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218.0,RED RIVER,4202,1.0,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209.0,RED RIVER,4205,20.0,1.707027e+06,659887.471571
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207.0,WASTE IND,2206,2.0,1.735692e+06,685027.245923
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209.0,RED RIVER,4203,20.0,1.710186e+06,664205.101066

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
zip_col = pd.to_numeric(df['Zip Code'], errors='coerce') # converts zip to numeric & errors to NaN
df['Zip Code'] = zip_col.fillna(0).astype('int64') # fill NaN values with 0 and convert to integer

In [7]:
cd_col = pd.to_numeric(df['Council District'], errors='coerce') # converts cd to numeric & errors to NaN
df['Council District'] = cd_col.fillna(0).astype('int64') # fill NaN values with 0 and convert to integer

In [8]:
tr_col = pd.to_numeric(df['Trash Route'], errors='coerce') # converts cd to numeric & errors to NaN
df['Trash Route'] = tr_col.fillna(0).astype('int64') # fill NaN values with 0 and convert to integer

In [9]:
df.head()

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2,1.727970e+06,686779.478089
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20,1.707027e+06,659887.471571
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207,WASTE IND,2206,2,1.735692e+06,685027.245923
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209,RED RIVER,4203,20,1.710186e+06,664205.101066

In [10]:
df = df.drop_duplicates() #drop dupes and save to df
df

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2,1.727970e+06,686779.478089
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20,1.707027e+06,659887.471571
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207,WASTE IND,2206,2,1.735692e+06,685027.245923
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209,RED RIVER,4203,20,1.710186e+06,664205.101066
...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013,RED RIVER,4502,32,1.781137e+06,632448.551144
20222,267126,11/01/19,Trash - Curbside/Alley Missed Pickup,entire alley,"1621 Long Ave, Nashville, TN 37206, United States",37206,METRO,9508,6,1.749711e+06,669201.601569
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,"2943 Windemere Cir, Nashville, TN 37214, Unite...",37214,RED RIVER,1502,15,1.770293e+06,674936.303809
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,"3325 Murfreesboro Pike, Nashville, TN 37013, U...",37013,RED RIVER,4502,32,1.785225e+06,627146.400187
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,"604 Somerset Ct, Nashville, TN 37217, United S...",37217,RED RIVER,2505,29,1.781360e+06,637742.006846

In [11]:
df['Incident Address'] = df['Incident Address'].str.split(',', n=1, expand=True)[0] #drops everything after first ',' in address

In [12]:
df

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2,1.727970e+06,686779.478089
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1,1.721259e+06,685444.799565
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20,1.707027e+06,659887.471571
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207,WASTE IND,2206,2,1.735692e+06,685027.245923
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209,RED RIVER,4203,20,1.710186e+06,664205.101066
...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013,RED RIVER,4502,32,1.781137e+06,632448.551144
20222,267126,11/01/19,Trash - Curbside/Alley Missed Pickup,entire alley,1621 Long Ave,37206,METRO,9508,6,1.749711e+06,669201.601569
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,2943 Windemere Cir,37214,RED RIVER,1502,15,1.770293e+06,674936.303809
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,3325 Murfreesboro Pike,37013,RED RIVER,4502,32,1.785225e+06,627146.400187
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,604 Somerset Ct,37217,RED RIVER,2505,29,1.781360e+06,637742.006846

In [13]:
df['Missed Count'] = df['Description'].str.contains('miss', case=False, na=False) #new column checking for 'miss' under 'Description'
count_by_address = df.groupby('Incident Address')['Missed Count'].sum().reset_index()
print(count_by_address)

                Incident Address  Missed Count
0                                            0
1          1 BELLE FORREST AVE C             1
2           10 Belle Forrest Ave             1
3           100 Bluefield Square             1
4            100 Braxton Hill Ct             1
...                          ...           ...
13393   compton ave & 15th ave s             0
13394              fransworth dr             1
13395   s 13th st  & woodland st             0
13396  trimble rd & lindawood dr             0
13397                  xavier dr             0

[13398 rows x 2 columns]

In [14]:
df

,Request Number,Date Opened,Request,Description,Incident Address,Zip Code,Trash Hauler,Trash Route,Council District,State Plan X,State Plan Y,Missed Count
0,25270,11/01/17,Trash - Backdoor,"house with the wheel chair ramp, they share dr...",3817 Crouch Dr,37207,RED RIVER,3205,2,1.727970e+06,686779.478089,False
1,25274,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/Trash miss Tuesday.,4028 Clarksville Pike,37218,RED RIVER,4202,1,1.721259e+06,685444.799565,True
2,25276,11/01/17,Trash - Curbside/Alley Missed Pickup,Curb/trash miss Tuesday.,6528 Thunderbird Dr,37209,RED RIVER,4205,20,1.707027e+06,659887.471571,True
3,25307,11/01/17,Trash - Curbside/Alley Missed Pickup,missed,2603 old matthews rd,37207,WASTE IND,2206,2,1.735692e+06,685027.245923,True
4,25312,11/01/17,Trash - Curbside/Alley Missed Pickup,Missed the even side of the road.,604 croley dr,37209,RED RIVER,4203,20,1.710186e+06,664205.101066,True
...,...,...,...,...,...,...,...,...,...,...,...,...
20221,267125,11/01/19,Trash - Curbside/Alley Missed Pickup,MISSED...NEIGHBORS MISSED,2731 Murfreesboro Pike,37013,RED RIVER,4502,32,1.781137e+06,632448.551144,True
20222,267126,11/01/19,Trash - Curbside/Alley Missed Pickup,entire alley,1621 Long Ave,37206,METRO,9508,6,1.749711e+06,669201.601569,False
20223,267130,11/01/19,Trash - Curbside/Alley Missed Pickup,missed several,2943 Windemere Cir,37214,RED RIVER,1502,15,1.770293e+06,674936.303809,True
20224,267134,11/01/19,Trash - Curbside/Alley Missed Pickup,Caller stated trash was missed & were only pic...,3325 Murfreesboro Pike,37013,RED RIVER,4502,32,1.785225e+06,627146.400187,True
20225,267137,11/01/19,Trash - Curbside/Alley Missed Pickup,possibly others missed as well,604 Somerset Ct,37217,RED RIVER,2505,29,1.781360e+06,637742.006846,True

In [15]:
#count_by_address['Total Fine'] = (count_by_address['Missed Count'] - 1) * 200 #-1 from missed_count and multiply by $200
#count_by_address['Total Fine'] = count_by_address['Total Fine'].clip(lower=0) #this gets rid of negative values as a result from 0 misses
#print(count_by_address)

In [17]:
#grand_total = count_by_address['Total Fine'].sum()
#print(f"Total amount owed due to missed pickups: ${grand_total}")

In [19]:
all_missed = df.loc[
    (df['Description'].str.contains('miss', case=False, na=False)) |  # Check for 'miss' in Description
    (df['Request '].str.contains('miss', case=False, na=False))  # Check for 'miss' in Request
]
print(all_missed)

       Request Number Date Opened                              Request   \
1               25274    11/01/17  Trash - Curbside/Alley Missed Pickup
2               25276    11/01/17  Trash - Curbside/Alley Missed Pickup
3               25307    11/01/17  Trash - Curbside/Alley Missed Pickup
4               25312    11/01/17  Trash - Curbside/Alley Missed Pickup
7               25327    11/01/17            Trash Collection Complaint
...               ...         ...                                   ...
20221          267125    11/01/19  Trash - Curbside/Alley Missed Pickup
20222          267126    11/01/19  Trash - Curbside/Alley Missed Pickup
20223          267130    11/01/19  Trash - Curbside/Alley Missed Pickup
20224          267134    11/01/19  Trash - Curbside/Alley Missed Pickup
20225          267137    11/01/19  Trash - Curbside/Alley Missed Pickup

                                             Description  \
1                               Curb/Trash miss Tuesday.
2                               Curb/trash miss Tuesday.
3                                                 missed
4                      Missed the even side of the road.
7           Trash out on time, miss again Tuesday. ALLEY
...                                                  ...
20221                          MISSED...NEIGHBORS MISSED
20222                                       entire alley
20223                                     missed several
20224  Caller stated trash was missed & were only pic...
20225                     possibly others missed as well

             Incident Address  Zip Code Trash Hauler  Trash Route  \
1       4028 Clarksville Pike     37218    RED RIVER         4202
2         6528 Thunderbird Dr     37209    RED RIVER         4205
3        2603 old matthews rd     37207    WASTE IND         2206
4               604 croley dr     37209    RED RIVER         4203
7        1816 Jo Johnston Ave     37203        METRO         9208
...                       ...       ...          ...          ...
20221  2731 Murfreesboro Pike     37013    RED RIVER         4502
20222           1621 Long Ave     37206        METRO         9508
20223      2943 Windemere Cir     37214    RED RIVER         1502
20224  3325 Murfreesboro Pike     37013    RED RIVER         4502
20225         604 Somerset Ct     37217    RED RIVER         2505

       Council District  State Plan X   State Plan Y  Missed Count
1                     1  1.721259e+06  685444.799565          True
2                    20  1.707027e+06  659887.471571          True
3                     2  1.735692e+06  685027.245923          True
4                    20  1.710186e+06  664205.101066          True
7                    21  1.731459e+06  666013.601229          True
...                 ...           ...            ...           ...
20221                32  1.781137e+06  632448.551144          True
20222                 6  1.749711e+06  669201.601569         False
20223                15  1.770293e+06  674936.303809          True
20224                32  1.785225e+06  627146.400187          True
20225                29  1.781360e+06  637742.006846          True

[17739 rows x 12 columns]

In [21]:
print(df.columns)

Index(['Request Number', 'Date Opened', 'Request ', 'Description',
       'Incident Address', 'Zip Code', 'Trash Hauler', 'Trash Route',
       'Council District', 'State Plan X', 'State Plan Y', 'Missed Count'],
      dtype='object')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20226 entries, 0 to 20225
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Request Number    20226 non-null  int64
 1   Date Opened       20226 non-null  object
 2   Request           20226 non-null  object
 3   Description       20195 non-null  object
 4   Incident Address  20217 non-null  object
 5   Zip Code          20226 non-null  int64
 6   Trash Hauler      19325 non-null  object
 7   Trash Route       20226 non-null  int64
 8   Council District  20226 non-null  int64
 9   State Plan X      20198 non-null  float64
 10  State Plan Y      20198 non-null  float64
 11  Missed Count      20226 non-null  bool
dtypes: bool(1), float64(2), int64(4), object(5)
memory usage: 1.7+ MB

In [31]:
# Convert 'Description' and 'Request' to strings to handle any non-string data types
df['Description'] = df['Description'].fillna('').astype(str)
df['Request '] = df['Request '].fillna('').astype(str)

# Filter rows where 'miss' appears in 'Description' or 'Request'
all_missed = df.loc[
    (df['Description'].str.contains('miss', case=False, na=False)) |  # Check for 'miss' in Description
    (df['Request '].str.contains('miss', case=False, na=False))  # Check for 'miss' in Request
].copy()  # make a copy to avoid warning

# create a column for 'miss'
all_missed['Missed Count'] = all_missed.apply(
    lambda row: 1 if 'miss' in str(row['Description']).lower() else 0, axis=1
) + all_missed.apply(
    lambda row: 1 if 'miss' in str(row['Request ']).lower() else 0, axis=1
)
# Calculate the 'Total Fine' column based on the logic
all_missed['Total Fine'] = (all_missed['Missed Count'] - 1) * 200  # Subtract 1 from missed count and multiply by $200
all_missed['Total Fine'] = all_missed['Total Fine'].clip(lower=0)  # Get rid of negative fines

# Show the final DataFrame with the 'Total Fine' column
print(all_missed)

       Request Number Date Opened                              Request   \
1               25274    11/01/17  Trash - Curbside/Alley Missed Pickup
2               25276    11/01/17  Trash - Curbside/Alley Missed Pickup
3               25307    11/01/17  Trash - Curbside/Alley Missed Pickup
4               25312    11/01/17  Trash - Curbside/Alley Missed Pickup
7               25327    11/01/17            Trash Collection Complaint
...               ...         ...                                   ...
20221          267125    11/01/19  Trash - Curbside/Alley Missed Pickup
20222          267126    11/01/19  Trash - Curbside/Alley Missed Pickup
20223          267130    11/01/19  Trash - Curbside/Alley Missed Pickup
20224          267134    11/01/19  Trash - Curbside/Alley Missed Pickup
20225          267137    11/01/19  Trash - Curbside/Alley Missed Pickup

                                             Description  \
1                               Curb/Trash miss Tuesday.
2                               Curb/trash miss Tuesday.
3                                                 missed
4                      Missed the even side of the road.
7           Trash out on time, miss again Tuesday. ALLEY
...                                                  ...
20221                          MISSED...NEIGHBORS MISSED
20222                                       entire alley
20223                                     missed several
20224  Caller stated trash was missed & were only pic...
20225                     possibly others missed as well

             Incident Address  Zip Code Trash Hauler  Trash Route  \
1       4028 Clarksville Pike     37218    RED RIVER         4202
2         6528 Thunderbird Dr     37209    RED RIVER         4205
3        2603 old matthews rd     37207    WASTE IND         2206
4               604 croley dr     37209    RED RIVER         4203
7        1816 Jo Johnston Ave     37203        METRO         9208
...                       ...       ...          ...          ...
20221  2731 Murfreesboro Pike     37013    RED RIVER         4502
20222           1621 Long Ave     37206        METRO         9508
20223      2943 Windemere Cir     37214    RED RIVER         1502
20224  3325 Murfreesboro Pike     37013    RED RIVER         4502
20225         604 Somerset Ct     37217    RED RIVER         2505

       Council District  State Plan X   State Plan Y  Missed Count  Total Fine
1                     1  1.721259e+06  685444.799565             2         200
2                    20  1.707027e+06  659887.471571             2         200
3                     2  1.735692e+06  685027.245923             2         200
4                    20  1.710186e+06  664205.101066             2         200
7                    21  1.731459e+06  666013.601229             1           0
...                 ...           ...            ...           ...         ...
20221                32  1.781137e+06  632448.551144             2         200
20222                 6  1.749711e+06  669201.601569             1           0
20223                15  1.770293e+06  674936.303809             2         200
20224                32  1.785225e+06  627146.400187             2         200
20225                29  1.781360e+06  637742.006846             2         200

[17739 rows x 13 columns]

In [33]:
grand_total = all_missed['Total Fine'].sum()
print(f"Total amount owed due to missed pickups: ${grand_total}")

Total amount owed due to missed pickups: $2063800